-- function signOff()
--   if exports["isPed"]:isPed("myjob") == 'police' then
-- 		TriggerEvent('raid_clothes:inService', false)
-- 		TriggerServerEvent("TokoVoip:removePlayerFromAllRadio",GetPlayerServerId(PlayerId()))
-- 		TriggerServerEvent("jobssystem:jobs", "unemployed")
--     TriggerServerEvent("ev-signoff:duty", "police")
-- 		TriggerServerEvent('myskin_customization:wearSkin')
-- 		TriggerServerEvent('tattoos:retrieve')
-- 		TriggerServerEvent('Blemishes:retrieve')
-- 		TriggerEvent("police:noLongerCop")
-- 		TriggerEvent("logoffmedic")		
-- 		TriggerEvent("loggedoff")					
-- 		TriggerEvent('nowCopDeathOff')
-- 		TriggerEvent('nowCopSpawnOff')
-- 		TriggerEvent('nowMedicOff')
-- 		TriggerServerEvent("TokoVoip:clientHasSelecterCharecter")
-- 		SetPedRelationshipGroupHash(PlayerPedId(),`PLAYER`)
-- 		SetPedRelationshipGroupDefaultHash(PlayerPedId(),`PLAYER`)
-- 		SetPoliceIgnorePlayer(PlayerPedId(),false)
-- 		TriggerEvent("DoLongHudText",'Signed off Duty!',1)
--   elseif exports["isPed"]:isPed("myjob") == 'ems' then
--     TriggerServerEvent("TokoVoip:removePlayerFromAllRadio",GetPlayerServerId(PlayerId()))
--     TriggerServerEvent("jobssystem:jobs", "unemployed")
--     TriggerServerEvent("ev-signoff:duty", "ems")
--     TriggerServerEvent('myskin_customization:wearSkin')
--     TriggerServerEvent('tattoos:retrieve')
--     TriggerServerEvent('Blemishes:retrieve')
--     TriggerEvent("police:noLongerCop")
--     TriggerEvent("logoffmedic")		
--     TriggerEvent("loggedoff")					
--     TriggerEvent('nowCopDeathOff')
--     TriggerEvent('nowCopSpawnOff')
--     TriggerEvent('nowMedicOff')
--     TriggerServerEvent("TokoVoip:clientHasSelecterCharecter")
--     SetPedRelationshipGroupHash(PlayerPedId(),`PLAYER`)
--     SetPedRelationshipGroupDefaultHash(PlayerPedId(),`PLAYER`)
--     SetPoliceIgnorePlayer(PlayerPedId(),false)
--     TriggerEvent("DoLongHudText",'Signed off Duty!',1)
--   end
-- end

function signOff()
  local myJob = exports["isPed"]:isPed("myjob")
  print("myJob", myJob)
  local code = RPC.execute("ev-jobs:getCallsign", myJob)
  local name = exports["isPed"]:isPed("fullname")
  -- local dispatch = code.callsign .. " - " .. name
  TriggerServerEvent("TokoVoip:removePlayerFromAllRadio", GetPlayerServerId(PlayerId()))
  exports["ev-voice"]:SetRadioPowerState(false)
  TriggerServerEvent("jobssystem:jobs", "unemployed")
  TriggerServerEvent('myskin_customization:wearSkin')
  TriggerServerEvent('Blemishes:retrieve')
  TriggerServerEvent('tattoos:retrieve')
  TriggerEvent("police:noLongerCop")
  TriggerEvent("logoffmedic")
  TriggerEvent("loggedoff")
  TriggerEvent('nowCopDeathOff')
  TriggerEvent('nowCopSpawnOff')
  TriggerEvent('nowMedicOff')
  TriggerEvent('ev-signin:signoff')
  TriggerServerEvent("blipOffDuty", myJob)
  TriggerServerEvent("TokoVoip:clientHasSelecterCharacter")
  -- TriggerServerEvent("dispatch:signoff", code.callsign, dispatch)
  SetPedRelationshipGroupHash(PlayerPedId(),`PLAYER`)
  SetPedRelationshipGroupDefaultHash(PlayerPedId(),`PLAYER`)
  SetPoliceIgnorePlayer(PlayerPedId(),false)
  TriggerEvent("isJudgeOff")
  TriggerEvent("DoLongHudText", 'Signed off Duty!', 1)
end

